---

  - name: Traefik | Check installed
    shell: test -x {{ traefik_bin_path }}
    register: traefik_exists
    changed_when: False
    ignore_errors: true
    tags:
      - statping
      - skip_ansible_lint


  - name: Traefik | Configure directories
    file: path="{{ item }}" state=directory
    with_items:
      - "{{ traefik_install_dir }}"
      - "{{ traefik_install_dir }}/conf.d"
    become: yes
    tags:
      - traefik
      - create
      - update

  - name: Detect traefik version - is first
    set_fact:
      traefik_family: 1
    when: traefik_version is version_compare('2', '<')

  - name: Detect traefik version - is second or above
    set_fact:
      traefik_family: 2
    when: traefik_version is version_compare('2', '>=')

  - name: Traefik | Configure wildcard conf.d/*.toml configuration
    template:
      src: "{{ role_dir }}/templates/traefik{{ traefik_family }}.toml.j2"
      dest: "{{ traefik_install_dir }}/traefik.toml"
      owner: root
      group: root
      mode: 0644
    become: yes
    tags:
      - traefik
      - create

  - name: Traefik | Configure systemd startup (normal)
    template:
      src: "{{ role_dir }}/templates/systemd/traefik.service.j2"
      dest: "/etc/systemd/system/traefik.service"
      owner: root
      group: root
      mode: 0644
    when: not option_confd_fallback
    become: yes
    tags:
      - traefik
      - create

  - name: Traefik | Template compile confd script (confd fallback)
    template:
      src: "{{ role_dir }}/templates/traefik_compile_confd.sh.j2"
      dest: "{{ traefik_install_dir }}/traefik_compile_confd.sh"
      owner: root
      group: root
      mode: "u=rwx,g=rx,o=rx"
    when: option_confd_fallback
    become: yes
    tags:
      - traefik
      - create

  - name: Traefik | Configure default entry points
    template:
      src: "templates/entrypoints{{ traefik_family }}.toml.j2"
      dest: "{{ traefik_install_dir }}/conf.d/entrypoints.toml"
      owner: root
      group: root
      mode: 0644
    become: yes
    notify: restart-traefik
    when: option_traefik_conf_defaultentrypoints
    tags:
      - traefik
      - create

  - name: Traefik | Configure web administration backend
    template:
      src: "templates/web_backend{{ traefik_family }}.toml.j2"
      dest: "{{ traefik_install_dir }}/conf.d/web_backend.toml"
      owner: root
      group: root
      mode: 0644
    become: yes
    when: option_traefik_conf_webbackend
    notify: restart-traefik
    tags:
      - traefik
      - create

  - name: Traefik | Configure docker link
    template:
      src: "templates/docker{{ traefik_family }}.toml.j2"
      dest: "{{ traefik_install_dir }}/conf.d/docker.toml"
      owner: root
      group: root
      mode: 0644
    become: yes
    notify: restart-traefik
    when: option_traefik_conf_docker
    tags:
      - traefik
      - create

  - name: Traefik | Configure docker link
    template:
      src: "templates/acme{{ traefik_family }}.toml.j2"
      dest: "{{ traefik_install_dir }}/conf.d/acme.toml"
      owner: root
      group: root
      mode: 0644
    become: yes
    notify: restart-traefik
    when: option_traefik_conf_webacme
    tags:
      - traefik
      - create

  - name: Traefik | Configure systemd startup (confd fallback)
    template:
      src: "{{ role_dir }}/templates/systemd/traefik_confd.service.j2"
      dest: "/etc/systemd/system/traefik.service"
      owner: root
      group: root
      mode: 0644
    when: option_confd_fallback
    become: yes
    tags:
      - traefik
      - create


  - name: Traefik | Ensure service is stopped for idempotency update
    service: name="traefik" state="stopped"
    when: docker_test is not defined and traefik_exists is failed
    become: yes
    tags:
      - traefik
      - update

  - name: Traefik | Download Traefik binary
    get_url: url="{{ traefik_distribution_url }}" dest="{{ traefik_bin_path }}" owner="root" group="root" mode="0755" force="yes"
    become: yes
    register: new_traefik_binary_downloaded
    when: traefik_exists is failed
    tags:
      - traefik
      - create
      - update

  - name: Traefik | Ensure traefik service is enabled and started
    systemd:
      name: "traefik"
      state: started
      daemon_reload: yes
      enabled: yes
    become: yes
    when: docker_test is not defined
    changed_when: False
    tags:
      - traefik
      - create
      - update
